### ISSUE TITLE
Grafana dashboard for netapp trident monitor

### ISSUE THREAD

**Issue by arunbpt7** [YvosOnTheHub/LabNetApp#1]
Hi,
This is with reference to the issue #382.

https://github.com/YvosOnTheHub/LabNetApp/tree/master/Kubernetes_v2/Scenarios/Scenario03/3_Grafana

I used the sample Trident_Dashboard_20.07.json file in to grafana. and able to see them in the dashboard.
But it seems few of the metrics data are incorrect in the dashboad. I am more interested in below data .

The metric trident_volume_total_bytes value is very much acurate when query in promethues . But it is inaccute in the dashboards. Appriciate if someone can help me out. Is there any official dashboard template available in trident ?
{
"expr": "trident_volume_total_bytes / 1024 / 1024 / 1024",
"instant": true,
"refId": "A"
}
],
"timeFrom": null,
"timeShift": null,
"title": "Capacity provisioned by Trident (GB)",
"type": "stat"

**Comment by YvosOnTheHub** [comment]
very odd, I have the right result in my environment.
which Trident version are you using?

There are 2 main dashboards:
- Trident_Dashboard_20.01.json (compatible with Trident 20.01 & 20.04)
- Trident_Dashboard_20.07.json (compatible with Trident 20.07 minimum)

if you are using the right version of Trident, could you tell me a bit more about your environment? (type of driver used, ....)

**Comment by arunbpt7** [comment]
we use trident version 20.07 and soldfire backend. when query trident_volume_total_bytes metric in promethues it returned with the correct values of sum of all the PV's. But when  use the the dashbord JSON in grafana , it always returned with inaccurate values all the times.

rident_Dashboard_20.07.json  was used . Attached is the screen shot from prom and grafana.

![grafana](https://user-images.githubusercontent.com/18433900/97483148-7873a680-192d-11eb-885c-49924ecb8a40.jpg)
![prom](https://user-images.githubusercontent.com/18433900/97483151-7a3d6a00-192d-11eb-9a70-52553c419db3.jpg)

**Comment by YvosOnTheHub** [comment]
got it, true that I have only tested this with ONTAP
let me do some digging

**Comment by YvosOnTheHub** [comment]
in my environment, it is all accurate ...
I am using Grafana 7.0.3 in my lab.

I notice from your picture that there is another difference.
In my lab, I dont see a "graph" in the "Capacity provisioned by Trident" box.

Did you edit this dashboard to get this different display?
![prometheus](https://user-images.githubusercontent.com/24714301/97542257-bc66ba00-19c6-11eb-901d-aeb176cf1e16.JPG)
![Grafana](https://user-images.githubusercontent.com/24714301/97542268-c12b6e00-19c6-11eb-9823-2fb80e96588b.JPG)

**Comment by arunbpt7** [comment]
No , i didnt edit the dashboard . The "Capacity provisioned by Trident"  graph is available in the Trident_Dashboard_20.07.json file. it it is starting from line 380 to 431. 

Environment is 
trident version : 20.07.0
backend : solidfire
storage driver: solidfire-san
grafana version : 6.7.2




================
{
      "datasource": "default",
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "decimals": 2,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "dark-blue",
                "value": null
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 3,
        "w": 4,
        "x": 14,
        "y": 0
      },
      "id": 14,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "mean"
          ],
          "fields": "",
          "values": true
        }
      },
      "pluginVersion": "7.0.3",
      "targets": [
        {
          "expr": "trident_volume_total_bytes / 1024 / 1024 / 1024",
          "instant": true,
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Capacity  provisioned by Trident (GB)",
      "type": "stat"
    },
===================

**Comment by YvosOnTheHub** [comment]
What does the graph "Trident Management over Time" display?
(I find it odd to see "A-Series" in the x-axis)

**Comment by arunbpt7** [comment]
pfa ,
![Image](https://user-images.githubusercontent.com/18433900/97707221-585af900-1a8d-11eb-86e0-3a018c03ee43.jpeg)


Also noticed that "Capacity mounted by kubelet(GB)  and Cluster version aalso shows inaccurate.

however Cluster version actually uses  "trident_build_info metric and it return value of "1" in promethues  as well.

**Comment by YvosOnTheHub** [comment]
did you import this dashboard recently?
I would recommend re-importing this dashboard, as it works well on my side.

if that does not fix anything, we can plan a zoom session sometimes next week

**Comment by arunbpt7** [comment]
yes , i did re-export is on multiple clusters ..  its not working perfectly

**Comment by YvosOnTheHub** [comment]
"not" or "now" ? (I wish for the "now")

**Comment by arunbpt7** [comment]
I did redeploy grafana using this dashboard multiple times recently after your last message. But it is still giving incorrect values for the mentioned fields.

**Comment by arunbpt7** [comment]
I have changed the datasource for those display  and it works fine  now

**Comment by YvosOnTheHub** [comment]
great !
I will remember that if it ever comes back 
thanks for the feedback
